### ISSUE TITLE
无法与mc服务端建立连接

### ISSUE THREAD

**Issue by YuYue-Amatsuki** [17TheWord/nonebot-adapter-minecraft#34]
当服务端尝试与nonebot建立连接时，nonebot提示403
```bash
05-26 22:48:10 [INFO] uvicorn | ('127.0.0.1', 51824) - "WebSocket /minecraft/ws" 403
05-26 22:48:10 [INFO] websockets | connection failed (403 Forbidden)
05-26 22:48:10 [INFO] websockets | connection closed
```
mc服务端日志如下
```bash
mcqq client reconnect
[22:48:05 INFO]: 即将重新连接未处于开启状态的 Websocket Client...
[22:48:05 INFO]: 正在尝试重连至：ws://127.0.0.1:11451/minecraft/ws 的 WebSocket 服务器...
[22:48:05 INFO]: 重连完成
[22:48:10 INFO]: [MC_QQ] 连接至：ws://127.0.0.1:11451/minecraft/ws 的 WebSocket 连接已断开，尝试第 4 次重连...
```
mc服务端的配置如下
```yml
# WebSocket Server配置项
websocket_server:
  enable: true
  host: "127.0.0.1"
  port: 8089

# 请在冒号后填写 WebSocket 地址。
# 默认：ws://127.0.0.1:8080/minecraft/ws
websocket_client:
  enable: true
  url_list:
    - "ws://127.0.0.1:11451/minecraft/ws"
```
nonebot的配置如下
```
HOST=127.0.0.1  # 配置 NoneBot2 监听的 IP/主机名
PORT=11451  # 配置 NoneBot2 监听的端口
SUPERUSERS=["245*****73"]  # 配置 NoneBot 超级用户
NICKNAME=["awesome", "bot"]  # 配置机器人的昵称
COMMAND_START=["/", "","#"]  # 配置命令起始字符
COMMAND_SEP=["."]  # 配置命令分割字符
DRIVER=~fastapi+~httpx+~websockets
mc_qq__say_way = "："
mc_qq__server_dict = '{
    "SkyLine Server": {
        "group_list": [
            {
                "group_id": "97*****92",
                "adapter": "onebot",
                "bot_id": "25*****89"
            }
        ],
        "guild_list": [
            {
                "guild_id": "",
                "channel_id": "",
                "adapter": "qq",
                "bot_id": ""
            }
        ],
        "rcon_msg": false,
        "rcon_cmd": true
    }
}'
minecraft_ws_urls = '{
    "SkyLine Server": ["ws://127.0.0.1:8089"]
}'
minecraft_server_rcon = '{
    "SkyLine Server": {
        "enable_rcon": true,
        "rcon_port": 25575,
        "rcon_password": ""
    }
}'
mc_qq__rcon_click_action_enable = true
mc_qq__rcon_hover_event_enable = true
mc_qq__rcon_text_component_status = 2
```
